server:
  port: 7500

spring:
  application:
    name: payment-system
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:192.168.3.36:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}

rocketmq:
  name-server: ${ROCKETMQ_NAMESRV_ADDR:192.168.3.36:9876}
  producer:
    group: payment-system-producer-group

# Knife4j API文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn
  production: false

# 日志配置
logging:
  level:
    root: INFO
    com.duanyan.payment: DEBUG
