server:
  port: 8086

spring:
  application:
    name: seckill-service
  config:
    import:
      - optional:nacos:backend-common.yaml?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}&refreshEnabled=true
      - optional:nacos:${spring.application.name}.yaml?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}&refreshEnabled=true

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:192.168.3.36:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        server-addr: ${NACOS_SERVER_ADDR:192.168.3.36:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_CONFIG_NAMESPACE:}
        file-extension: yaml
