server:
  port: 8086

spring:
  application:
    name: seckill-service

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6349
      password: 7566
      database: 0
      timeout: 5000

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        ip: 127.0.0.1  # 强制使用本地IP注册

knife4j:
  enable: true
  setting:
    language: zh_cn
  production: false

# RocketMQ 配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: seckill-service-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
  consumer:
    group: seckill-service-consumer-group

tpp:
  rocketmq:
    topic-bootstrap:
      enabled: true

logging:
  level:
    root: INFO
    com.duanyan.taopiaopiao: INFO
