CREATE TABLE IF NOT EXISTS lock_orders (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    lock_id VARCHAR(64) NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    request_id VARCHAR(64) DEFAULT NULL,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    seat_ids_json JSON NOT NULL,
    seat_count INT NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    status INT NOT NULL,
    expire_time DATETIME DEFAULT NULL,
    fail_reason VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_lock_orders_lock_id (lock_id),
    UNIQUE KEY uk_lock_orders_order_no (order_no),
    KEY idx_lock_orders_user_id (user_id),
    KEY idx_lock_orders_session_id (session_id),
    KEY idx_lock_orders_status_updated_at (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
